name: virtual_humans
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.9.9
  - numpy=1.22.3
  - requests=2.27.1
  - black=22.3.0
  - dlib=19.23.1
  - pytorch=1.10.0
  - scikit-image=0.19.2
  - pip=22.0.4
  - pillow=9.0.1
  - matplotlib=3.5.1
  - ipython
  - pip:
    - opencv-python==4.5.5.64
    - tensorflow-gpu==2.8.0
    - keras==2.8.0